apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: longhorn
  namespace: argocd
spec:
  description: Longhorn storage system
  sourceRepos:
    - "*"
  destinations:
    - namespace: longhorn-system
      server: https://kubernetes.default.svc
  clusterResourceWhitelist:
    - group: "*"
      kind: "*"
