apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: longhorn
  namespace: argocd
spec:
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
  project: default
  sources:
    - chart: longhorn
      repoURL: https://charts.longhorn.io/
      targetRevision: v1.8.2
      helm:
        values: |
          preUpgradeChecker:
            jobEnabled: false
          manager:
            readinessProbe:
              httpGet:
                path: /v1/healthz
                port: 9501
                scheme: HTTP
              initialDelaySeconds: 30
              periodSeconds: 10
              timeoutSeconds: 5
              failureThreshold: 6
  destination:
    server: https://kubernetes.default.svc
    namespace: longhorn-system
